services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - core
      - plugin-example-react-18
    networks:
      - external-network
      - internal-network

  core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core
    ports:
      - "3000:3000"
      - "4000:4000" # Port for HMR
    volumes:
      - ./core:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_WEBPACK_USEPOLLING=1
    networks:
      - internal-network

  # Plugins
  plugin-example-react-18:
    build:
      context: ./plugins/plugin-example-react-18
      dockerfile: Dockerfile
    container_name: plugin-example-react-18
    expose:
      - "3001"
    networks:
      - internal-network
  plugin-example-react-19:
    build:
      context: ./plugins/plugin-example-react-19
      dockerfile: Dockerfile
    container_name: plugin-example-react-19
    expose:
      - "3002"
    networks:
      - internal-network

networks:
  external-network:
  internal-network:
    internal: true
